const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Incident = sequelize.define('Incident', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  incidentNumber: { type: DataTypes.STRING(32), allowNull: false, unique: true, field: 'incident_number' },
  title: { type: DataTypes.STRING(255), allowNull: false },
  description: { type: DataTypes.TEXT, allowNull: false },
  category: { type: DataTypes.STRING(100), allowNull: false },
  subcategory: { type: DataTypes.STRING(100), allowNull: true },
  priority: { type: DataTypes.STRING(20), allowNull: false, defaultValue: 'medium' },
  impact: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'individual' },
  urgency: { type: DataTypes.STRING(20), allowNull: false, defaultValue: 'medium' },
  status: { type: DataTypes.STRING(30), allowNull: false, defaultValue: 'new' },
  reporterId: { type: DataTypes.INTEGER, allowNull: false, field: 'reporter_id' },
  employeeId: { type: DataTypes.INTEGER, allowNull: true, field: 'employee_id' },
  departmentId: { type: DataTypes.INTEGER, allowNull: true, field: 'department_id' },
  assetId: { type: DataTypes.INTEGER, allowNull: true, field: 'asset_id' },
  locationId: { type: DataTypes.INTEGER, allowNull: true, field: 'location_id' },
  assignedTechnicianId: { type: DataTypes.INTEGER, allowNull: true, field: 'assigned_technician_id' },
  supportTeam: { type: DataTypes.STRING(120), allowNull: true, field: 'support_team' },
  escalationLevel: { type: DataTypes.STRING(80), allowNull: true, field: 'escalation_level' },
  escalatedTo: { type: DataTypes.STRING(120), allowNull: true, field: 'escalated_to' },
  escalationReason: { type: DataTypes.TEXT, allowNull: true, field: 'escalation_reason' },
  reportedAt: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW, field: 'reported_at' },
  dueDate: { type: DataTypes.DATE, allowNull: true, field: 'due_date' },
  targetResolutionDate: { type: DataTypes.DATE, allowNull: true, field: 'target_resolution_date' },
  resolvedAt: { type: DataTypes.DATE, allowNull: true, field: 'resolved_at' },
  closedAt: { type: DataTypes.DATE, allowNull: true, field: 'closed_at' },
  resolvedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'resolved_by' },
  closedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'closed_by' },
  reopenedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'reopened_by' },
  reopenedAt: { type: DataTypes.DATE, allowNull: true, field: 'reopened_at' },
  reopenReason: { type: DataTypes.TEXT, allowNull: true, field: 'reopen_reason' },
  resolutionSummary: { type: DataTypes.TEXT, allowNull: true, field: 'resolution_summary' },
  rootCause: { type: DataTypes.TEXT, allowNull: true, field: 'root_cause' },
  resolutionType: { type: DataTypes.STRING(80), allowNull: true, field: 'resolution_type' },
  preventiveAction: { type: DataTypes.TEXT, allowNull: true, field: 'preventive_action' },
  slaStatus: { type: DataTypes.STRING(30), allowNull: true, field: 'sla_status' },
  responseDeadline: { type: DataTypes.DATE, allowNull: true, field: 'response_deadline' },
  resolutionDeadline: { type: DataTypes.DATE, allowNull: true, field: 'resolution_deadline' },
  isRecurring: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'is_recurring' },
  parentIncidentId: { type: DataTypes.INTEGER, allowNull: true, field: 'parent_incident_id' },
}, {
  tableName: 'incidents',
  timestamps: true,
  indexes: ['incident_number', 'status', 'priority', 'category', 'reporter_id', 'assigned_technician_id', 'asset_id', 'department_id', 'location_id', 'created_at', 'due_date'].map((fields) => ({ fields: [fields] })),
});

module.exports = Incident;
