const router = require('express').Router();
const { requirePermission } = require('../middlewares/auth');
const { requireDepartmentHead, resolveDepartmentScope } = require('../middlewares/organizationScope');
const { getDepartmentDashboard, listDepartmentAssets, listDepartmentStaff, listDepartmentLocations, getDepartmentReports, getDepartmentProfile, updateDepartmentProfile } = require('../controllers/departmentController');
const { listRequests, getRequest, createRequest } = require('../controllers/workspaceRequestController');
const verification = require('../controllers/verificationController');
const physicalVerification = require('../controllers/departmentVerificationController');
const maintenance = require('../controllers/maintenanceRequestWorkflowController');
const laboratories = require('../controllers/departmentLaboratoryController');
const assetRequests = require('../controllers/departmentAssetRequestController');
const departmentHistory = require('../controllers/departmentHistoryController');
const tickets = require('../controllers/departmentTicketController');
const assignmentRoutes = require('./assignmentRoutes');
const approvalAction = (decision) => (req, res, next) => {
  req.approvalDecision = decision;
  return assetRequests.decideApproval(req, res, next);
};

router.use(...requireDepartmentHead, resolveDepartmentScope);
router.get('/profile', requirePermission('department.profile.view'), getDepartmentProfile);
router.put('/profile', requirePermission('department.profile.update'), updateDepartmentProfile);
router.get('/dashboard', getDepartmentDashboard);
router.get('/assets', listDepartmentAssets);
router.get('/staff', listDepartmentStaff);
router.get('/locations', (req, res, next) => {
  if (String(req.query.export || '').toLowerCase() !== 'true') return next();
  return requirePermission('reports.export')(req, res, next);
}, listDepartmentLocations);
router.get('/laboratories', laboratories.listLaboratories);
router.get('/laboratories/:id', laboratories.getLaboratoryDashboard);
router.get('/reports', getDepartmentReports);
router.get('/history', requirePermission('department_head.history.view'), departmentHistory.getDepartmentHistory);
router.get('/asset-history', requirePermission('department_head.history.view'), departmentHistory.getDepartmentAssetHistory);
router.get('/inventory', getDepartmentDashboard);
router.get('/requests', listRequests);
router.post('/requests', createRequest);
router.get('/requests/:id', getRequest);
router.get('/asset-requests', assetRequests.listRequests);
router.post('/asset-requests', assetRequests.createRequest);
router.get('/asset-requests/:id', assetRequests.getRequest);
router.post('/asset-requests/:id/submit', assetRequests.submitDraft);
router.get('/approvals', requirePermission('department_head.approvals.review'), assetRequests.listApprovalQueue);
router.get('/approvals/:id', requirePermission('department_head.approvals.review'), assetRequests.getApprovalReview);
router.post('/approvals/:id/approve', requirePermission('department_head.approvals.approve'), approvalAction('approve'));
router.post('/approvals/:id/reject', requirePermission('department_head.approvals.reject'), approvalAction('reject'));
router.post('/approvals/:id/request-changes', requirePermission('department_head.approvals.request_changes'), approvalAction('request-changes'));
router.post('/approvals/:id/escalate', requirePermission('department_head.approvals.escalate'), approvalAction('escalate'));
router.get('/verification/history', physicalVerification.listVerifications);
router.post('/verification/records', physicalVerification.createVerification);
router.get('/verification', verification.listSessions);
router.post('/verification', verification.createSession);
router.get('/verification/:id', verification.getSession);
router.post('/verification/:id/items', verification.addItem);
router.post('/verification/:id/submit', verification.submitSession);
router.post('/verification/:id/finalize', verification.finalizeSession);
router.get('/maintenance', requirePermission('department_head.maintenance.view'), maintenance.getOversightList);
router.post('/maintenance', requirePermission('department_head.maintenance.view'), maintenance.createRequest);
router.get('/maintenance/:id', requirePermission('department_head.maintenance.view'), maintenance.getOversightDetail);
router.post('/maintenance/:id/cancel', requirePermission('department_head.maintenance.view'), maintenance.cancelRequest);
router.get('/maintenance-requests', maintenance.listRequests);
router.post('/maintenance-requests', maintenance.createRequest);
router.get('/tickets', requirePermission('department_head.tickets.view'), tickets.listTickets);
router.get('/escalated-tickets', requirePermission('department_head.tickets.view'), tickets.listEscalatedTickets);
router.get('/tickets/escalated', requirePermission('department_head.tickets.view'), tickets.listEscalatedTickets);
router.post('/tickets/:id/follow-up', requirePermission('department_head.tickets.follow_up'), tickets.addTicketFollowUp);
router.get('/tickets/:id', requirePermission('department_head.tickets.view'), tickets.getTicket);
router.use('/assignments', requirePermission('assets.view'), assignmentRoutes);

module.exports = router;
