// Role Constants
// Define all user roles in the system

export const ROLES = {
  ADMIN: 'admin',
  ICT_OFFICER: 'ict_officer',
  COLLEGE: 'college',
  COLLEGE_HEAD: 'college',
  DEPARTMENT_HEAD: 'college',
  FINANCE_MANAGER: 'finance',
  MAINTENANCE_STAFF: 'maintenance',
  STORE_MANAGER: 'store_manager',
  INFRASTRUCTURE: 'infrastructure',
  USER: 'user'
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    'view_all_assets',
    'create_asset',
    'edit_asset',
    'delete_asset',
    'manage_users',
    'manage_departments',
    'view_reports',
    'manage_backups',
    'system_settings'
  ],
  [ROLES.ICT_OFFICER]: [
    'ict.dashboard.view',
    'ict.assets.view',
    'ict.assets.create',
    'ict.assets.update',
    'ict.assets.assign',
    'ict.assets.transfer',
    'ict.assets.return',
    'ict.assets.history.view',
    'ict.inspection.view',
    'ict.inspection.create',
    'ict.inspection.update',
    'ict.rfid.view',
    'ict.rfid.create',
    'ict.rfid.update',
    'ict.rfid.track',
    'ict.maintenance.view',
    'ict.maintenance.create',
    'ict.maintenance.update',
    'ict.security.view',
    'ict.security.update',
    'ict.software.view',
    'ict.software.create',
    'ict.software.update',
    'ict.hardware.view',
    'ict.hardware.update',
    'ict.reports.view',
    'ict.reports.export',
    'ict.notifications.view',
    'ict.notifications.update'
  ],
  [ROLES.COLLEGE]: [
    'college.dashboard.view',
    'college.assets.view',
    'college.assets.history.view',
    'college.staff.view',
    'college.requests.view',
    'college.requests.create',
    'college.requests.update',
    'college.requests.submit',
    'college.approvals.view',
    'college.approvals.approve',
    'college.approvals.reject',
    'college.assignments.view',
    'college.assignments.confirm',
    'college.transfers.view',
    'college.transfers.create',
    'college.transfers.approve',
    'college.returns.view',
    'college.returns.request',
    'college.returns.confirm',
    'college.maintenance.view',
    'college.maintenance.create',
    'college.maintenance.approve',
    'college.rfid.view',
    'college.rfid.track',
    'college.reports.view',
    'college.reports.export',
    'college.notifications.view',
    'college.notifications.update'
  ],
  [ROLES.COLLEGE_HEAD]: [
    'college.dashboard.view',
    'college.assets.view',
    'college.assets.history.view',
    'college.staff.view',
    'college.requests.view',
    'college.requests.create',
    'college.requests.update',
    'college.requests.submit',
    'college.approvals.view',
    'college.approvals.approve',
    'college.approvals.reject',
    'college.assignments.view',
    'college.assignments.confirm',
    'college.transfers.view',
    'college.transfers.create',
    'college.transfers.approve',
    'college.returns.view',
    'college.returns.request',
    'college.returns.confirm',
    'college.maintenance.view',
    'college.maintenance.create',
    'college.maintenance.approve',
    'college.rfid.view',
    'college.rfid.track',
    'college.reports.view',
    'college.reports.export',
    'college.notifications.view',
    'college.notifications.update'
  ],
  [ROLES.FINANCE_MANAGER]: [
    'finance.dashboard.view',
    'finance.purchases.view',
    'finance.purchases.create',
    'finance.purchases.update',
    'finance.purchases.approve',
    'finance.purchases.reject',
    'finance.invoices.view',
    'finance.invoices.create',
    'finance.invoices.update',
    'finance.invoices.verify',
    'finance.payments.view',
    'finance.payments.create',
    'finance.payments.update',
    'finance.budget.view',
    'finance.budget.create',
    'finance.budget.update',
    'finance.assets.view',
    'finance.assets.financial.update',
    'finance.depreciation.view',
    'finance.depreciation.calculate',
    'finance.depreciation.update',
    'finance.suppliers.view',
    'finance.suppliers.create',
    'finance.suppliers.update',
    'finance.reports.view',
    'finance.reports.export',
    'finance.notifications.view',
    'finance.notifications.update',
    'finance.transactions.view'
  ],
  [ROLES.INFRASTRUCTURE]: [
    'infrastructure.dashboard.view',
    'infrastructure.assets.view',
    'infrastructure.assets.create',
    'infrastructure.assets.update',
    'infrastructure.maintenance.view',
    'infrastructure.workorders.view',
    'infrastructure.tracking.view',
    'infrastructure.reports.view',
    'infrastructure.audit.view',
    'infrastructure.notifications.view'
  ],
  [ROLES.MAINTENANCE_STAFF]: [
    'maintenance.dashboard.view',
    'maintenance.requests.view',
    'maintenance.requests.create',
    'maintenance.requests.update',
    'maintenance.requests.approve',
    'maintenance.requests.reject',
    'maintenance.inspection.view',
    'maintenance.inspection.create',
    'maintenance.inspection.update',
    'maintenance.workorders.view',
    'maintenance.workorders.create',
    'maintenance.workorders.update',
    'maintenance.workorders.assign',
    'maintenance.repairs.view',
    'maintenance.repairs.create',
    'maintenance.repairs.update',
    'maintenance.preventive.view',
    'maintenance.preventive.create',
    'maintenance.preventive.update',
    'maintenance.technicians.view',
    'maintenance.technicians.create',
    'maintenance.technicians.update',
    'maintenance.parts.view',
    'maintenance.parts.create',
    'maintenance.parts.update',
    'maintenance.parts.issue',
    'maintenance.costs.view',
    'maintenance.costs.create',
    'maintenance.testing.view',
    'maintenance.testing.create',
    'maintenance.testing.update',
    'maintenance.history.view',
    'maintenance.reports.view',
    'maintenance.reports.export',
    'maintenance.notifications.view',
    'maintenance.notifications.update'
  ],
  [ROLES.STORE_MANAGER]: [
    'view_inventory',
    'manage_stock',
    'view_store_reports'
  ],
  [ROLES.USER]: [
    'view_own_assets',
    'request_maintenance'
  ]
};

export const ROLE_LABELS = {
  [ROLES.ADMIN]: 'Administrator',
  [ROLES.ICT_OFFICER]: 'ICT Officer',
  [ROLES.COLLEGE]: 'College Head',
  [ROLES.COLLEGE_HEAD]: 'College Head',
  [ROLES.FINANCE_MANAGER]: 'Finance Manager',
  [ROLES.MAINTENANCE_STAFF]: 'Maintenance Staff',
  [ROLES.STORE_MANAGER]: 'Store Manager',
  [ROLES.INFRASTRUCTURE]: 'Infrastructure Director',
  [ROLES.USER]: 'User'
};
