// Route Constants
// Define all application routes

export const PUBLIC_ROUTES = [
  '/login',
  '/register',
  '/forgot-password',
  '/home',
  '/about',
  '/contact'
];

export const ROUTES = {
  // Public Routes
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/home',
  ABOUT: '/about',
  CONTACT: '/contact',

  // Admin Routes
  ADMIN_DASHBOARD: '/admin',
  ADMIN_ASSETS: '/admin/assets',
  ADMIN_ASSET_CATEGORIES: '/admin/assets/categories',
  ADMIN_CREATE_ASSET: '/admin/assets/create',
  ADMIN_ASSIGNMENT: '/admin/assets/assign',
  ADMIN_TRANSFER: '/admin/assets/transfer',
  ADMIN_DISPOSAL: '/admin/assets/disposal',
  ADMIN_MAINTENANCE: '/admin/maintenance',
  ADMIN_RFID: '/admin/rfid',
  ADMIN_ANALYTICS_ASSETS: '/admin/analytics/assets',
  ADMIN_ANALYTICS_SYSTEM: '/admin/analytics/system',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/users/roles',
  ADMIN_PERMISSIONS: '/admin/users/permissions',
  ADMIN_COLLEGES: '/admin/colleges',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_BACKUP: '/admin/backup',
  ADMIN_DEPARTMENTS: '/admin/departments',
  ADMIN_LOCATIONS: '/admin/locations',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_MONITORING: '/admin/monitoring',

  // ICT Officer Routes
  ICT_DASHBOARD: '/ict',
  ICT_ASSETS: '/ict/assets',
  ICT_CREATE_ASSET: '/ict/assets/create',
  ICT_ASSIGNMENTS: '/ict/assets/assign',
  ICT_ASSET_REQUESTS: '/ict/requests',
  ICT_MAINTENANCE: '/ict/maintenance',
  ICT_MAINTENANCE_REPAIR_HISTORY: '/ict/repair-history',
  ICT_MAINTENANCE_DEVICE_HEALTH: '/ict/device-health',
  ICT_RFID: '/ict/rfid',
  ICT_REPORTS: '/ict/reports',
  ICT_ASSET_ANALYTICS: '/ict/analytics/assets',
  ICT_INVENTORY: '/ict/inventory',
  ICT_NOTIFICATIONS: '/ict/notifications',
  ICT_ASSET_HISTORY: '/ict/assets/history',
  ICT_EQUIPMENT: '/ict/equipment',
  ICT_NETWORK: '/ict/network',
  ICT_SOFTWARE_LICENSES: '/ict/software-licenses',
  ICT_SUPPORT: '/ict/support',
  ICT_INCIDENTS: '/ict/incidents',
  ICT_REPAIR_HISTORY: '/ict/repair-history',
  ICT_DEVICE_HEALTH: '/ict/device-health',
  ICT_ASSET_ANALYTICS_ALIAS: '/ict/asset-analytics',

  // College Routes
  DEPT_DASHBOARD: '/college',
  DEPT_PROFILE: '/college/profile',
  DEPT_COLLEGE_STAFF: '/college/staff',
  DEPT_LOCATIONS: '/college/locations',
  DEPT_DEPARTMENTS: '/college/departments',
  DEPT_ASSETS: '/college/assets',
  DEPT_INVENTORY: '/college/inventory',
  DEPT_REQUESTS: '/college/requests',
  DEPT_APPROVALS: '/college/approvals',
  DEPT_ASSIGNMENTS: '/college/assignments',
  DEPT_TRANSFERS: '/college/transfers',
  DEPT_RETURNS: '/college/returns',
  DEPT_MAINTENANCE: '/college/maintenance',
  DEPT_RFID: '/college/rfid',
  DEPT_VERIFICATION: '/college/verification',
  DEPT_REPORTS: '/college/reports',
  DEPT_ASSET_ANALYTICS: '/college/analytics/assets',
  DEPT_DEPARTMENT_REPORTS: '/college/analytics/departments',
  DEPT_DEPARTMENT_OVERVIEW: '/college/department-overview',
  DEPT_DEPARTMENT_STAFF: '/college/department-staff',
  DEPT_DEPARTMENT_ASSETS: '/college/department-assets',
  DEPT_DEPARTMENT_REQUESTS: '/college/department-requests',
  DEPT_DEPARTMENT_PERFORMANCE: '/college/department-performance',
  DEPT_STAFF: '/college/staff',
  DEPT_NOTIFICATIONS: '/college/notifications',
  DEPT_ASSET_HISTORY: '/college/history',

  // Finance Routes
  FINANCE_DASHBOARD: '/finance',
  FINANCE_PURCHASE_REQUESTS: '/finance/purchase-requests',
  FINANCE_PURCHASE_ORDERS: '/finance/purchase-orders',
  FINANCE_SUPPLIERS: '/finance/suppliers',
  FINANCE_PURCHASE_HISTORY: '/finance/purchase-history',
  FINANCE_INVOICES: '/finance/invoices',
  FINANCE_PAYMENTS: '/finance/payments',
  FINANCE_TRANSACTIONS: '/finance/transactions',
  FINANCE_BUDGET: '/finance/budget',
  FINANCE_BUDGET_MANAGEMENT: '/finance/budget-management',
  FINANCE_VALUATION: '/finance/valuation',
  FINANCE_DEPRECIATION: '/finance/depreciation',
  FINANCE_CAPITALIZATION: '/finance/capitalization',
  FINANCE_DISPOSAL_FINANCIAL_RECORDS: '/finance/disposal-financial-records',
  FINANCE_FINANCIAL_REPORTS: '/finance/financial-reports',
  FINANCE_BUDGET_REPORTS: '/finance/budget-reports',
  FINANCE_DEPRECIATION_REPORTS: '/finance/depreciation-reports',
  FINANCE_ASSET_VALUE_REPORTS: '/finance/asset-value-reports',
  FINANCE_AUDIT: '/finance/audit',
  FINANCE_NOTIFICATIONS: '/finance/notifications',

  // Maintenance Routes
  MAINT_DASHBOARD: '/maintenance',
  MAINT_REQUESTS: '/maintenance/requests',
  MAINT_INSPECTION: '/maintenance/inspection',
  MAINT_WORK_ORDERS: '/maintenance/work-orders',
  MAINT_REPAIRS: '/maintenance/repairs',
  MAINT_SCHEDULE: '/maintenance/schedule',
  MAINT_PREVENTIVE: '/maintenance/preventive',
  MAINT_CALENDAR: '/maintenance/calendar',
  MAINT_TECHNICIANS: '/maintenance/technicians',
  MAINT_PARTS: '/maintenance/spare-parts',
  MAINT_ASSETS: '/maintenance/assets-under-maintenance',
  MAINT_VENDORS: '/maintenance/vendors',
  MAINT_TESTING: '/maintenance/testing-quality',
  MAINT_QUALITY_CONTROL: '/maintenance/quality-control',
  MAINT_ASSIGNED: '/maintenance/assigned-tasks',
  MAINT_HISTORY: '/maintenance/history',
  MAINT_COST_ANALYSIS: '/maintenance/cost-analysis',
  MAINT_REPORTS: '/maintenance/reports',
  MAINT_NOTIFICATIONS: '/maintenance/notifications',

  // Store Routes
  STORE_DASHBOARD: '/store',
  STORE_INVENTORY: '/store/inventory',
  STORE_AVAILABLE_ASSETS: '/store/available-assets',
  STORE_LOW_STOCK: '/store/low-stock',
  STORE_STOCK_ADJUSTMENTS: '/store/stock-adjustments',
  STORE_ASSETS: '/store/assets',
  STORE_RECEIVE: '/store/receive',
  STORE_ISSUE: '/store/issue',
  STORE_RETURNS: '/store/returns',
  STORE_TRANSFERS: '/store/transfers',
  STORE_ASSET_REQUESTS: '/store/requests',
  STORE_TRACKING: '/store/tracking',
  STORE_HISTORY: '/store/history',
  STORE_ASSET_MOVEMENT_HISTORY: '/store/history',
  STORE_ASSET_VERIFICATION: '/store/verification',
  STORE_MAINTENANCE: '/store/maintenance',
  STORE_MAINTENANCE_STATUS: '/store/maintenance/status',
  STORE_WARRANTY: '/store/warranty',
  STORE_REPORTS: '/store/reports',
  STORE_INVENTORY_REPORTS: '/store/reports/inventory',
  STORE_ISSUE_REPORTS: '/store/reports/issues',
  STORE_RETURN_REPORTS: '/store/reports/returns',
  STORE_MOVEMENT_REPORTS: '/store/reports/movements',
  STORE_NOTIFICATIONS: '/store/notifications',

  // Shared Routes
  ASSETS: '/assets',
  ASSET_DETAILS: '/assets/:id',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile'
};

export const getRoutesByRole = (role) => {
  const routesByRole = {
    admin: [
      ROUTES.ADMIN_DASHBOARD,
      ROUTES.ADMIN_ASSETS,
      ROUTES.ADMIN_ASSET_CATEGORIES,
      ROUTES.ADMIN_ASSIGNMENT,
      ROUTES.ADMIN_TRANSFER,
      ROUTES.ADMIN_DISPOSAL,
      ROUTES.ADMIN_MAINTENANCE,
      ROUTES.ADMIN_RFID,
      ROUTES.ADMIN_USERS,
      ROUTES.ADMIN_ROLES,
      ROUTES.ADMIN_COLLEGES,
      ROUTES.ADMIN_DEPARTMENTS,
      ROUTES.ADMIN_LOCATIONS,
      ROUTES.ADMIN_REPORTS,
      ROUTES.ADMIN_ANALYTICS_ASSETS,
      ROUTES.ADMIN_ANALYTICS_SYSTEM,
      ROUTES.ADMIN_SETTINGS,
      ROUTES.ADMIN_NOTIFICATIONS,
      ROUTES.ADMIN_AUDIT_LOGS,
      ROUTES.ADMIN_BACKUP,
      ROUTES.ADMIN_MONITORING
    ],
    ict_officer: [
      ROUTES.ICT_DASHBOARD,
      ROUTES.ICT_ASSETS,
      ROUTES.ICT_CREATE_ASSET,
      ROUTES.ICT_INVENTORY,
      ROUTES.ICT_ASSIGNMENTS,
      ROUTES.ICT_ASSET_REQUESTS,
      ROUTES.ICT_EQUIPMENT,
      ROUTES.ICT_NETWORK,
      ROUTES.ICT_SOFTWARE_LICENSES,
      ROUTES.ICT_SUPPORT,
      ROUTES.ICT_INCIDENTS,
      ROUTES.ICT_MAINTENANCE,
      ROUTES.ICT_MAINTENANCE_REPAIR_HISTORY,
      ROUTES.ICT_MAINTENANCE_DEVICE_HEALTH,
      ROUTES.ICT_RFID,
      ROUTES.ICT_ASSET_HISTORY,
      ROUTES.ICT_REPORTS,
      ROUTES.ICT_ASSET_ANALYTICS_ALIAS,
      ROUTES.ICT_NOTIFICATIONS
    ],
    college: [
      ROUTES.DEPT_DASHBOARD,
      ROUTES.DEPT_PROFILE,
      ROUTES.DEPT_COLLEGE_STAFF,
      ROUTES.DEPT_LOCATIONS,
      ROUTES.DEPT_DEPARTMENTS,
      ROUTES.DEPT_ASSETS,
      ROUTES.DEPT_INVENTORY,
      ROUTES.DEPT_REQUESTS,
      ROUTES.DEPT_APPROVALS,
      ROUTES.DEPT_ASSIGNMENTS,
      ROUTES.DEPT_TRANSFERS,
      ROUTES.DEPT_RETURNS,
      ROUTES.DEPT_DEPARTMENT_OVERVIEW,
      ROUTES.DEPT_DEPARTMENT_STAFF,
      ROUTES.DEPT_DEPARTMENT_ASSETS,
      ROUTES.DEPT_DEPARTMENT_REQUESTS,
      ROUTES.DEPT_DEPARTMENT_PERFORMANCE,
      ROUTES.DEPT_MAINTENANCE,
      ROUTES.DEPT_RFID,
      ROUTES.DEPT_VERIFICATION,
      ROUTES.DEPT_REPORTS,
      ROUTES.DEPT_ASSET_ANALYTICS,
      ROUTES.DEPT_DEPARTMENT_REPORTS,
      ROUTES.DEPT_NOTIFICATIONS,
      ROUTES.DEPT_ASSET_HISTORY
    ],
    department_head: [
      ROUTES.DEPT_DASHBOARD,
      ROUTES.DEPT_PROFILE,
      ROUTES.DEPT_ASSETS,
      ROUTES.DEPT_REQUESTS,
      ROUTES.DEPT_APPROVALS,
      ROUTES.DEPT_ASSIGNMENTS,
      ROUTES.DEPT_TRANSFERS,
      ROUTES.DEPT_RETURNS,
      ROUTES.DEPT_MAINTENANCE,
      ROUTES.DEPT_RFID,
      ROUTES.DEPT_REPORTS,
      ROUTES.DEPT_STAFF,
      ROUTES.DEPT_NOTIFICATIONS,
      ROUTES.DEPT_ASSET_HISTORY
    ],
    finance: [
      ROUTES.FINANCE_DASHBOARD,
      ROUTES.FINANCE_PURCHASE_REQUESTS,
      ROUTES.FINANCE_PURCHASE_ORDERS,
      ROUTES.FINANCE_SUPPLIERS,
      ROUTES.FINANCE_PURCHASE_HISTORY,
      ROUTES.FINANCE_INVOICES,
      ROUTES.FINANCE_PAYMENTS,
      ROUTES.FINANCE_TRANSACTIONS,
      ROUTES.FINANCE_BUDGET,
      ROUTES.FINANCE_BUDGET_MANAGEMENT,
      ROUTES.FINANCE_VALUATION,
      ROUTES.FINANCE_DEPRECIATION,
      ROUTES.FINANCE_CAPITALIZATION,
      ROUTES.FINANCE_DISPOSAL_FINANCIAL_RECORDS,
      ROUTES.FINANCE_FINANCIAL_REPORTS,
      ROUTES.FINANCE_BUDGET_REPORTS,
      ROUTES.FINANCE_DEPRECIATION_REPORTS,
      ROUTES.FINANCE_ASSET_VALUE_REPORTS,
      ROUTES.FINANCE_AUDIT,
      ROUTES.FINANCE_NOTIFICATIONS
    ],
    maintenance: [
      ROUTES.MAINT_DASHBOARD,
      ROUTES.MAINT_REQUESTS,
      ROUTES.MAINT_INSPECTION,
      ROUTES.MAINT_WORK_ORDERS,
      ROUTES.MAINT_REPAIRS,
      ROUTES.MAINT_SCHEDULE,
      ROUTES.MAINT_PREVENTIVE,
      ROUTES.MAINT_CALENDAR,
      ROUTES.MAINT_TECHNICIANS,
      ROUTES.MAINT_PARTS,
      ROUTES.MAINT_ASSETS,
      ROUTES.MAINT_VENDORS,
      ROUTES.MAINT_TESTING,
      ROUTES.MAINT_QUALITY_CONTROL,
      ROUTES.MAINT_ASSIGNED,
      ROUTES.MAINT_HISTORY,
      ROUTES.MAINT_COST_ANALYSIS,
      ROUTES.MAINT_REPORTS,
      ROUTES.MAINT_NOTIFICATIONS
    ],
    store: [
      ROUTES.STORE_DASHBOARD,
      ROUTES.STORE_INVENTORY,
      ROUTES.STORE_AVAILABLE_ASSETS,
      ROUTES.STORE_LOW_STOCK,
      ROUTES.STORE_STOCK_ADJUSTMENTS,
      ROUTES.STORE_RECEIVE,
      ROUTES.STORE_ISSUE,
      ROUTES.STORE_RETURNS,
      ROUTES.STORE_TRANSFERS,
      ROUTES.STORE_ASSET_REQUESTS,
      ROUTES.STORE_TRACKING,
      ROUTES.STORE_ASSET_MOVEMENT_HISTORY,
      ROUTES.STORE_ASSET_VERIFICATION,
      ROUTES.STORE_MAINTENANCE,
      ROUTES.STORE_MAINTENANCE_STATUS,
      ROUTES.STORE_INVENTORY_REPORTS,
      ROUTES.STORE_ISSUE_REPORTS,
      ROUTES.STORE_RETURN_REPORTS,
      ROUTES.STORE_MOVEMENT_REPORTS,
      ROUTES.STORE_NOTIFICATIONS
    ],
    store_manager: [
      ROUTES.STORE_DASHBOARD,
      ROUTES.STORE_INVENTORY,
      ROUTES.STORE_AVAILABLE_ASSETS,
      ROUTES.STORE_LOW_STOCK,
      ROUTES.STORE_STOCK_ADJUSTMENTS,
      ROUTES.STORE_ASSETS,
      ROUTES.STORE_RECEIVE,
      ROUTES.STORE_ISSUE,
      ROUTES.STORE_RETURNS,
      ROUTES.STORE_TRANSFERS,
      ROUTES.STORE_ASSET_REQUESTS,
      ROUTES.STORE_TRACKING,
      ROUTES.STORE_HISTORY,
      ROUTES.STORE_ASSET_VERIFICATION,
      ROUTES.STORE_MAINTENANCE,
      ROUTES.STORE_MAINTENANCE_STATUS,
      ROUTES.STORE_REPORTS,
      ROUTES.STORE_INVENTORY_REPORTS,
      ROUTES.STORE_ISSUE_REPORTS,
      ROUTES.STORE_RETURN_REPORTS,
      ROUTES.STORE_MOVEMENT_REPORTS,
      ROUTES.STORE_NOTIFICATIONS
    ],
    user: [ROUTES.ASSETS, ROUTES.NOTIFICATIONS, ROUTES.SETTINGS]
  };

  return routesByRole[role] || [];
};
