CREATE TABLE IF NOT EXISTS financial_transactions (
  id INT NOT NULL AUTO_INCREMENT,
  transaction_number VARCHAR(100) NOT NULL,
  type ENUM('debit', 'credit') NOT NULL,
  category VARCHAR(100) NULL,
  transaction_type VARCHAR(50) NULL,
  status ENUM('pending', 'posted', 'voided') NOT NULL DEFAULT 'pending',
  amount DECIMAL(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
  transaction_date DATE NOT NULL,
  reference_type ENUM('invoice', 'payment', 'purchase_order', 'budget', 'asset', 'other') NOT NULL DEFAULT 'other',
  reference_id INT NULL,
  reference_number VARCHAR(100) NULL,
  supplier_id INT NULL,
  supplier_name VARCHAR(255) NULL,
  account_code VARCHAR(50) NULL,
  account_name VARCHAR(255) NULL,
  description TEXT NULL,
  department_id INT NULL,
  department_name VARCHAR(255) NULL,
  created_by INT NOT NULL,
  posted_by INT NULL,
  posted_at DATETIME NULL,
  voided_by INT NULL,
  voided_at DATETIME NULL,
  void_reason TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY financial_transactions_number_uq (transaction_number),
  KEY financial_transactions_status_idx (status),
  KEY financial_transactions_type_idx (type),
  KEY financial_transactions_date_idx (transaction_date),
  KEY financial_transactions_reference_idx (reference_type, reference_id),
  KEY financial_transactions_supplier_idx (supplier_id),
  CONSTRAINT financial_transactions_amount_positive CHECK (amount > 0),
  CONSTRAINT financial_transactions_creator_fk FOREIGN KEY (created_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT financial_transactions_poster_fk FOREIGN KEY (posted_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT financial_transactions_voider_fk FOREIGN KEY (voided_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT financial_transactions_supplier_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;
