CREATE TABLE IF NOT EXISTS finance_transactions (
  id INT NOT NULL AUTO_INCREMENT,
  transaction_number VARCHAR(100) NOT NULL,
  transaction_date DATE NOT NULL,
  transaction_type VARCHAR(50) NOT NULL DEFAULT 'Payment',
  reference_type VARCHAR(100) NULL,
  reference_id INT NULL,
  reference_number VARCHAR(100) NULL,
  account_code VARCHAR(50) NULL,
  account_name VARCHAR(255) NULL,
  description TEXT NULL,
  supplier_id INT NULL,
  supplier_name VARCHAR(255) NULL,
  department_id INT NULL,
  department_name VARCHAR(255) NULL,
  amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'ETB',
  debit DECIMAL(15, 2) NOT NULL DEFAULT 0,
  credit DECIMAL(15, 2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(50) NULL,
  bank_name VARCHAR(255) NULL,
  bank_reference VARCHAR(100) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Posted',
  notes TEXT NULL,
  created_by INT NOT NULL,
  updated_by INT NULL,
  deleted_by INT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY finance_transactions_number_uq (transaction_number),
  KEY finance_transactions_date_id_idx (transaction_date, id),
  KEY finance_transactions_status_date_idx (status, transaction_date),
  KEY finance_transactions_type_date_idx (transaction_type, transaction_date),
  KEY finance_transactions_reference_date_idx (reference_type, transaction_date),
  CONSTRAINT finance_transactions_amount_nonnegative CHECK (amount >= 0 AND debit >= 0 AND credit >= 0),
  CONSTRAINT finance_transactions_creator_fk FOREIGN KEY (created_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT finance_transactions_updater_fk FOREIGN KEY (updated_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT finance_transactions_deleter_fk FOREIGN KEY (deleted_by) REFERENCES users (id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;
