import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Ban, BadgeCheck, CheckCircle, ClipboardCheck, Clock3, Eye, FileText, History, LoaderCircle, MapPin, Package, PackageCheck, RefreshCw, Search, SlidersHorizontal, Undo2, UserRound, X } from 'lucide-react';
import { apiClient } from '../../utils/api';
import './DepartmentReturnsPage.css';

const reasons = ['End of Assignment', 'Replacement', 'Damage', 'Maintenance', 'Employee Transfer', 'Employee Separation', 'Department Transfer', 'Temporary Return', 'Inventory Verification', 'Other'];
const conditions = ['Excellent', 'Good', 'Fair', 'Poor', 'Damaged', 'Non-functional'];
const initialForm = { asset_id: '', reason: reasons[0], condition: 'Good', notes: '' };
const listData = (payload, key) => (Array.isArray(payload) ? payload : payload?.data || payload?.[key] || []).filter(Boolean);
const label = (value) => value || 'Not recorded';

const StatusBadge = ({ status }) => {
  const value = String(status || 'Unknown');
  const Icon = value === 'Returned' || value === 'Received' || value === 'Inspected' ? BadgeCheck : value === 'Rejected' || value === 'Cancelled' ? Ban : value === 'Approved' ? CheckCircle : value === 'Ready for Return' ? LoaderCircle : Clock3;
  return <span className={`return-status status-${value.toLowerCase().replaceAll(' ', '-')}`}><Icon size={14} />{value}</span>;
};

export default function DepartmentReturnsPage() {
  const [rows, setRows] = useState([]); const [assignments, setAssignments] = useState([]); const [selected, setSelected] = useState(null);
  const [form, setForm] = useState(initialForm); const [search, setSearch] = useState(''); const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [formError, setFormError] = useState(''); const [showForm, setShowForm] = useState(false); const [processingId, setProcessingId] = useState(null);

  const load = useCallback(async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true); setError('');
    try {
      const [returnsResponse, assignmentsResponse] = await Promise.all([
        apiClient.get('/api/department/returns', { params: { pageSize: 100, search: search || undefined, status: status || undefined } }),
        apiClient.get('/api/assignments', { params: { limit: 100, status: 'active' } }),
      ]);
      setRows(listData(returnsResponse.data, 'returns')); setAssignments(listData(assignmentsResponse.data, 'assignments'));
    } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load asset returns.'); }
    finally { setLoading(false); setRefreshing(false); }
  }, [search, status]);

  useEffect(() => { load(); }, [load]);
  const eligibleAssets = useMemo(() => assignments.filter((item) => String(item.status).toLowerCase() === 'active' && item.asset_id), [assignments]);
  const selectedAssignment = eligibleAssets.find((item) => String(item.asset_id) === String(form.asset_id));
  const summary = useMemo(() => ({ total: rows.length, pending: rows.filter((row) => row.status === 'Requested').length, processing: rows.filter((row) => ['Approved', 'Ready for Return', 'Received'].includes(row.status)).length, completed: rows.filter((row) => row.status === 'Inspected').length, rejected: rows.filter((row) => ['Rejected', 'Cancelled'].includes(row.status)).length }), [rows]);

  const submit = async (event) => {
    event.preventDefault(); setFormError('');
    if (!form.asset_id || !form.reason) return setFormError('Select an assigned asset and return reason.');
    if (['Damage', 'Other'].includes(form.reason) && form.notes.trim().length < 5) return setFormError('Add at least five characters explaining this return.');
    setSaving(true);
    try { await apiClient.post('/api/department/returns', { ...form }); setShowForm(false); setForm(initialForm); await load(true); }
    catch (requestError) { setFormError(requestError.response?.data?.message || 'Unable to submit the return request.'); }
    finally { setSaving(false); }
  };

  const openDetails = async (row) => { setSelected(row); try { const response = await apiClient.get(`/api/department/returns/${row.id}`); setSelected(response.data?.data || row); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load return details.'); } };
  const cancel = async (row) => { if (!window.confirm(`Cancel the return request for ${row.asset_name || 'this asset'}?`)) return; setProcessingId(row.id); try { await apiClient.post(`/api/department/returns/${row.id}/cancel`); await load(true); setSelected(null); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to cancel the return request.'); } finally { setProcessingId(null); } };

  return <main className="department-returns-page">
    <header className="department-returns-header"><div><div className="returns-eyebrow"><Undo2 size={16} /> Department Operations</div><h1>Asset Returns</h1><p>Request and track the return of assets assigned within your department.</p></div><div className="returns-header-actions"><button type="button" className="returns-secondary" onClick={() => load(true)} disabled={refreshing}><RefreshCw size={16} className={refreshing ? 'spin' : ''} /> Refresh</button><button type="button" className="returns-primary" onClick={() => { setForm(initialForm); setFormError(''); setShowForm(true); }}><PackageCheck size={16} /> Request Return</button></div></header>
    <section className="returns-summary">{[[Package, summary.total, 'Total Returns'], [Clock3, summary.pending, 'Pending'], [LoaderCircle, summary.processing, 'Processing'], [BadgeCheck, summary.completed, 'Completed'], [Ban, summary.rejected, 'Rejected / Cancelled']].map(([Icon, value, text]) => <div className="return-summary-card" key={text}><Icon size={18} /><strong>{value}</strong><span>{text}</span></div>)}</section>
    <section className="returns-toolbar"><div className="returns-search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search asset, code, serial number or return ID" aria-label="Search returns" /></div><div className="returns-filter"><SlidersHorizontal size={16} /><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option value="">All statuses</option>{['Requested', 'Approved', 'Ready for Return', 'Received', 'Inspected', 'Rejected', 'Cancelled'].map((item) => <option key={item}>{item}</option>)}</select></div>{(search || status) && <button type="button" className="clear-filter" onClick={() => { setSearch(''); setStatus(''); }}>Clear filters</button>}</section>
    {error && <div className="returns-alert"><X size={18} /> <span>{error}</span><button type="button" onClick={() => load()}>Retry</button></div>}
    {loading ? <div className="returns-state"><RefreshCw size={22} className="spin" /> Loading asset returns...</div> : <section className="returns-table-card"><div className="returns-table-title"><div><h2>Return requests</h2><span>{rows.length} records in your authorized scope</span></div><History size={20} /></div>{rows.length === 0 ? <div className="returns-empty"><Package size={30} /><strong>No asset returns found</strong><span>{search || status ? 'Clear filters to view all asset returns.' : 'Create a request when an assigned asset needs to be returned.'}</span></div> : <div className="returns-table-wrap"><table><thead><tr><th>Return ID</th><th>Asset</th><th>Assigned To</th><th>Location</th><th>Condition</th><th>Status</th><th>Last Updated</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.return_number || row.returnNumber || `Return #${row.id}`}</strong></td><td><div className="asset-cell"><Package size={16} /><span>{label(row.asset_name)}<small>{row.asset_code || row.serial_number || 'No asset code'}</small></span></div></td><td>{label(row.source_user_name || row.requester_name)}</td><td><span className="location-cell"><MapPin size={14} />{label(row.asset_location)}</span></td><td>{label(row.condition)}</td><td><StatusBadge status={row.status} /></td><td>{row.updatedAt ? new Date(row.updatedAt).toLocaleDateString() : 'Not recorded'}</td><td><button type="button" className="icon-action" title="View return details" aria-label="View return details" onClick={() => openDetails(row)}><Eye size={16} /></button>{['Requested', 'Approved'].includes(row.status) && <button type="button" className="icon-action danger" title="Cancel return request" aria-label="Cancel return request" onClick={() => cancel(row)} disabled={processingId === row.id}><Ban size={16} /></button>}</td></tr>)}</tbody></table></div>}</section>}
    {showForm && <div className="returns-dialog-backdrop"><div className="returns-dialog" role="dialog" aria-modal="true" aria-labelledby="return-form-title"><div className="dialog-heading"><div><span className="returns-eyebrow"><PackageCheck size={16} /> New request</span><h2 id="return-form-title">Request asset return</h2></div><button type="button" className="icon-action" onClick={() => setShowForm(false)} aria-label="Close"><X size={18} /></button></div><form onSubmit={submit}><label>Assigned asset <span>*</span><select required value={form.asset_id} onChange={(event) => setForm({ ...form, asset_id: event.target.value })}><option value="">Select an eligible assigned asset</option>{eligibleAssets.map((item) => <option key={item.asset_id} value={item.asset_id}>{item.asset_name || 'Unnamed asset'} ({item.asset_tag || item.asset_id})</option>)}</select></label>{selectedAssignment ? <div className="assignment-context"><div><UserRound size={15} /><span>Custodian<strong>{label(selectedAssignment.assigned_to_name)}</strong></span></div><div><MapPin size={15} /><span>Location<strong>{label(selectedAssignment.location)}</strong></span></div><div><ClipboardCheck size={15} /><span>Assignment date<strong>{selectedAssignment.assigned_date ? new Date(selectedAssignment.assigned_date).toLocaleDateString() : 'Not recorded'}</strong></span></div></div> : <div className="form-empty">{eligibleAssets.length ? 'Select an asset to review its current assignment.' : 'No assets are currently available for return.'}</div>}<label>Return reason <span>*</span><select required value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })}>{reasons.map((item) => <option key={item}>{item}</option>)}</select></label><label>Return condition<select value={form.condition} onChange={(event) => setForm({ ...form, condition: event.target.value })}>{conditions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Notes<textarea rows="4" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Add context for the receiving team" /></label>{formError && <div className="form-error">{formError}</div>}<div className="dialog-actions"><button type="button" className="returns-secondary" onClick={() => setShowForm(false)}>Cancel</button><button type="submit" className="returns-primary" disabled={saving || !eligibleAssets.length}>{saving ? <><LoaderCircle size={16} className="spin" /> Submitting...</> : <><PackageCheck size={16} /> Submit request</>}</button></div></form></div></div>}
    {selected && <div className="returns-dialog-backdrop"><div className="returns-dialog details-dialog" role="dialog" aria-modal="true" aria-labelledby="return-detail-title"><div className="dialog-heading"><div><span className="returns-eyebrow"><FileText size={16} /> Return record</span><h2 id="return-detail-title">{selected.return_number || `Return #${selected.id}`}</h2></div><button type="button" className="icon-action" onClick={() => setSelected(null)} aria-label="Close"><X size={18} /></button></div><div className="detail-status"><StatusBadge status={selected.status} /><span>Last updated {selected.updatedAt ? new Date(selected.updatedAt).toLocaleString() : 'not recorded'}</span></div><div className="detail-grid">{[['Asset', selected.asset_name], ['Asset code', selected.asset_code], ['Serial number', selected.serial_number], ['Category', selected.asset_category], ['Asset status', selected.asset_status], ['Assigned to', selected.source_user_name || selected.requester_name], ['Department', selected.department], ['Location', selected.asset_location], ['Reason', selected.reason], ['Condition', selected.condition], ['Requested by', selected.requester_name], ['Return date', selected.receivedAt ? new Date(selected.receivedAt).toLocaleString() : 'Not processed']].map(([name, value]) => <div key={name}><small>{name}</small><strong>{label(value)}</strong></div>)}<div className="detail-notes"><small><FileText size={14} /> Notes</small><p>{label(selected.notes)}</p></div></div></div></div>}
  </main>;
}
